import Head from 'next/head';
import Header from './components/Header';
import Bookform from './components/Bookform';
import Footer from './components/Footer';

// import styles from '../styles/Home.module.css'

export default function Home() {
    
    return (
        <div>
            <Head>
                <title>TravelLodge Dome Hotel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                {/* <script src="./script.js" type="text/javascript"></script> */}
            </Head>
            
            <Header />

            <Bookform />

            <Footer />


        </div>
    )
}
