import Head from 'next/head';
import Header from './components/Header';
import Content from './components/Content';
import Footer from './components/Footer';

import { Helmet } from "react-helmet";

// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TravelLodge Dome Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Helmet>
          <script src="./script.js"
            type="text/javascript" />
        </Helmet>
      </Head>

      <Header />

      <Content />

      <Footer />

      
    </div>
  )
}
